<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
=======
<testng-results ignored="1" total="2" passed="1" failed="0" skipped="0">
>>>>>>> branch 'master' of https://github.com/StringManu/4haSWP.git
  <reporter-output>
  </reporter-output>
<<<<<<< HEAD
  <suite started-at="2024-11-05T11:15:19 MEZ" name="Default suite" finished-at="2024-11-05T11:15:19 MEZ" duration-ms="119">
=======
  <suite started-at="2024-11-05T11:43:24 MEZ" name="Default suite" finished-at="2024-11-05T11:43:24 MEZ" duration-ms="51">
>>>>>>> branch 'master' of https://github.com/StringManu/4haSWP.git
    <groups>
    </groups>
<<<<<<< HEAD
    <test started-at="2024-11-05T11:15:19 MEZ" name="Default test" finished-at="2024-11-05T11:15:19 MEZ" duration-ms="119">
      <class name="exceptionsTesting.TestAufgabe3">
        <test-method signature="testAufgabe3_1()[pri:0, instance:exceptionsTesting.TestAufgabe3@41e1e210]" started-at="2024-11-05T11:15:19 MEZ" name="testAufgabe3_1" finished-at="2024-11-05T11:15:19 MEZ" duration-ms="21" status="PASS">
=======
    <test started-at="2024-11-05T11:43:24 MEZ" name="Default test" finished-at="2024-11-05T11:43:24 MEZ" duration-ms="51">
      <class name="exceptionsTesting.Test_Aufgabe4">
        <test-method signature="testReadFile2()[pri:0, instance:exceptionsTesting.Test_Aufgabe4@272ed83b]" started-at="2024-11-05T11:43:24 MEZ" name="testReadFile2" finished-at="2024-11-05T11:43:24 MEZ" duration-ms="10" status="PASS">
>>>>>>> branch 'master' of https://github.com/StringManu/4haSWP.git
          <reporter-output>
          </reporter-output>
<<<<<<< HEAD
        </test-method> <!-- testAufgabe3_1 -->
        <test-method signature="testAufgabe3_2()[pri:0, instance:exceptionsTesting.TestAufgabe3@41e1e210]" started-at="2024-11-05T11:15:19 MEZ" name="testAufgabe3_2" finished-at="2024-11-05T11:15:19 MEZ" duration-ms="2" status="FAIL">
          <exception class="exceptionsTesting.InvalidNumberException">
            <message>
              <![CDATA[Needs to be a number!]]>
            </message>
            <full-stacktrace>
              <![CDATA[exceptionsTesting.InvalidNumberException: Needs to be a number!
at exceptionsTesting.Aufgabe3.parseInt(Aufgabe3.java:9)
at exceptionsTesting.TestAufgabe3.testAufgabe3_2(TestAufgabe3.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- exceptionsTesting.InvalidNumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAufgabe3_2 -->
      </class> <!-- exceptionsTesting.TestAufgabe3 -->
=======
        </test-method> <!-- testReadFile2 -->
      </class> <!-- exceptionsTesting.Test_Aufgabe4 -->
>>>>>>> branch 'master' of https://github.com/StringManu/4haSWP.git
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
